### ISSUE TITLE
Crash when running with no env vars

### ISSUE THREAD

**Issue by alexh-sauce** [erikdubbelboer/gspt#14]
When gspt is run in a shell with no env vars, it crashes:

```go
package main

import (
        "github.com/erikdubbelboer/gspt"
)

func main() {
        gspt.SetProcTitle("^")
        select {}
}
```

Results in:

```bash
$ env -i ./gspt-test
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xfffffffffffffff0 pc=0x7f54c3cbe4e8]

runtime stack:
runtime.throw(0x49309a, 0x2a)
        /usr/local/go/src/runtime/panic.go:1117 +0x72
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:718 +0x2e5

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x473140, 0xc000039c40, 0x4810c0)
        /usr/local/go/src/runtime/cgocall.go:154 +0x5b fp=0xc000039c10 sp=0xc000039bd8 pc=0x404bdb
github.com/erikdubbelboer/gspt._Cfunc_spt_init2(0x1, 0x1954820)
        _cgo_gotypes.go:102 +0x3c fp=0xc000039c40 sp=0xc000039c10 pc=0x47255c
github.com/erikdubbelboer/gspt.init.0()
        /home/alexh/go/pkg/mod/github.com/erikdubbelboer/gspt@v0.0.0-20201015204752-6cb2489021da/gspt.go:52 +0x305 fp=0xc000039ce8 sp=0xc000039c40 pc=0x4729c5
runtime.doInit(0x4f9ca0)
        /usr/local/go/src/runtime/proc.go:6265 +0xec fp=0xc000039e38 sp=0xc000039ce8 pc=0x442d2c
runtime.doInit(0x4f8fa0)
        /usr/local/go/src/runtime/proc.go:6242 +0x72 fp=0xc000039f88 sp=0xc000039e38 pc=0x442cb2
runtime.main()
        /usr/local/go/src/runtime/proc.go:208 +0x205 fp=0xc000039fe0 sp=0xc000039f88 pc=0x4356c5
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc000039fe8 sp=0xc000039fe0 pc=0x461ce1
```

**Comment by erikdubbelboer** [comment]
Thanks for reporting this. It's fixed in: https://github.com/erikdubbelboer/gspt/commit/ce36a512837778923c9202c819eb6a3435f9d21d
When there is no env its also not possible/save to be able to set the proc title. The way this module works is by finding the command in memory and replacing it there. I'm afraid that is the only way. It's very hacky, and that's why it doesn't work without env.

**Comment by alexh-sauce** [comment]
Thanks for the fix! It's a weird edge case we discovered when running some integration tests, so not a problem in the real world.
