### ISSUE TITLE
Crash with long args

### ISSUE THREAD

**Issue by sj26** [erikdubbelboer/gspt#7]
Booting a go process with long args and this module imported causes a panic:

``` go
# main.go
package main

import _ "github.com/ErikDubbelboer/gspt"

func main() {}
```

```
$ go run main.go 0000... # 8192 zeroes
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x0 pc=0x407ba69]

runtime stack:
runtime.throw(0x40cbe80, 0x2a)
    .../libexec/src/runtime/panic.go:547 +0x90
runtime.sigpanic()
    .../libexec/src/runtime/sigpanic_unix.go:12 +0x5a

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x407b9a0, 0xc82004be20, 0xc800000000)
    .../libexec/src/runtime/cgocall.go:123 +0x11b fp=0xc82004bdd0 sp=0xc82004bda0
github.com/ErikDubbelboer/gspt._Cfunc_spt_init2(0x2, 0x4600aa0)
    github.com/ErikDubbelboer/gspt/_obj/_cgo_gotypes.go:89 +0x3a fp=0xc82004be20 sp=0xc82004bdd0
github.com/ErikDubbelboer/gspt.init.1()
    github.com/ErikDubbelboer/gspt/gspt.go:53 +0x427 fp=0xc82004bf40 sp=0xc82004be20
github.com/ErikDubbelboer/gspt.init()
    github.com/ErikDubbelboer/gspt/_obj/_cgo_import.go:1 +0x4a fp=0xc82004bf48 sp=0xc82004bf40
main.init()
    .../main.go:5 +0x3b fp=0xc82004bf50 sp=0xc82004bf48
runtime.main()
    .../libexec/src/runtime/proc.go:177 +0x27f fp=0xc82004bfa0 sp=0xc82004bf50
runtime.goexit()
    .../libexec/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82004bfa8 sp=0xc82004bfa0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    .../libexec/src/runtime/asm_amd64.s:1998 +0x1
exit status 2
```

I'm running go version go1.6.2 darwin/amd64 on OS X 10.11.5 installed via homebrew.

**Comment by erikdubbelboer** [comment]
I know it's because of this: https://github.com/erikdubbelboer/gspt/blob/6ce3e9d87b8c94ec4a633f85078de25981910124/setproctitle.h#L105
But I'm not sure how to fix it yet.

**Comment by erikh** [comment]
https://unix.stackexchange.com/questions/120642/what-defines-the-maximum-size-for-a-command-single-argument

I found this. HTH

**Comment by erikh** [comment]
it sounds like, you need to compute it from stack size and ARG_MAX, but I may be reading incorrectly.

**Comment by erikdubbelboer** [comment]
This should be fixed in https://github.com/erikdubbelboer/gspt/commit/e68493906b8382891943ddc9960cb9c6ecd1a1f0
It wasn't an `ARG_MAX` problem but a problem with some return value not being checked properly.
